# Generated by Django 5.2 on 2025-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='device',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'hall')},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='group',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='room',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
