# Generated by Django 5.2 on 2026-01-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group',
            name='intake',
            field=models.CharField(help_text='Program intake (e.g., FIT, FIS, FIM)', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
