# Generated by Django 5.2 on 2026-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_notification_is_read'),
        ('timetable', '0004_notificationread'),
    ]

    operations = [
    ]
